### ISSUE TITLE
plugin manager

### ISSUE THREAD

**Issue by ghost** [naus3a/NauModular#10]
Hi! 

I m helping Andrew with the plugin manager. I went throu all the module packs today and saw that you only provide Mac binaries. I wanted to know if you need someone to compile your modules for Windows and Linux? Because people like me can´t use your modules unless I compile them myself. Not everyone knows how to do that.

**Comment by AndrewBelt** [comment]
I think NauModular is the last remaining plugin not compiled for Windows, so I may remove it from the Plugin Manager in a few days since it confuses more people than helps.

**Comment by naus3a** [comment]
Hey,
if someone can compile a win and linux version for me, it would be great.
I want to make myself a win and linux dev environment at some point, but free time is scarce, so I don't really have an ETA and anyone's contribute is welcome :)

**Comment by ghost** [comment]
I tried to compile it but you make use of some stuff like <sys.select.h> and <arpa/inet.h> which gives me errors.. therefor it only can be compiled on windows (and maybe linux aswell) when changed (make use of something equivalent)

I m not so advanced to know what would work.. arpa/inet.h can be replaced with winsock2.h if I m not mistaken.. but thats about it :) 

  and your makefile is missing "VERSION = 0.5.1" or whatever your plugin version is...

**Comment by naus3a** [comment]
Yes: the current master has a osc module prototype and it needs some work.
Windows does sockets differently than other OSses, so I'll have to make a few #ifdef in order to make it work.
I also need to make a decent osc input logic.

You should probably be able to compile the commit I used for the latest mac release: https://github.com/naus3a/NauModular/tree/1d3ec3609e725a986359fa6751f610f5527b9809

Version should 0.5.2.
I hope to be able to make a cleaned up version with osc module soon: I let you decide if you want to compile the older commit, or if you prefer to wait for the new cleaned up release. I really appreciate your help, but I don't want to make you waste too much time :)

**Comment by cschol** [comment]
@AndrewBelt @Phal-anx Closing of #12 fixes the build issues on Windows.

**Comment by naus3a** [comment]
Well the plugin manager is gone for now in any case, so I guess we can close for now :)

**Comment by ghost** [comment]
it still needs to be updated .. otherwise your modules/plugin will disapear from it for good..

**Comment by cschol** [comment]
@Phal-anx The code compiles fine now on Windows. What else is needed?

EDIT: Here is a Windows build:

[NauModular-0.5.2-win.zip](https://github.com/naus3a/NauModular/files/1641580/NauModular-0.5.2-win.zip)

**Comment by AndrewBelt** [comment]
Actually I won't need to remove anything until the Plugin Manager for free third-party plugins is re-enabled, and I'll be overhauling a lot before then.
