### ISSUE TITLE
Perlin noise produced by the module seems to be a repeating pattern

### ISSUE THREAD

**Issue by odahan** [naus3a/NauModular#5]
The Perlin noise generator is always producing the same pattern. 
To reproduce : record the output and have a look to the signal, you'll see a single pattern being repeated.

Some ideas to correct this faulty behavior can perhaps be found here in this very short c++ Perlin implementation (I have not tested this code, just an idea to fix the Perlin generator) : 
https://github.com/Reputeless/PerlinNoise/blob/master/PerlinNoise.hpp

**Comment by naus3a** [comment]
Hey,
The noise modeling is still heavily in the design phase: I just quickly crammed in the fastest graphic noise code I had at hand, because I wanted to hear how it sounded like and to figure out how to interact with the virtual input voltages.

The next commit is probably going to be focused on trying a few different Perlin noise implementations I  normally use (c++ and glsl), make a benchmark and see what works best.
I'm probably going to experiment with time based noise modulation too, and see how it compares with the simple incremented value.

Thanks for taking the time to test and for the link!

**Comment by naus3a** [comment]
@odahan since the repetition bug you mention should not happen, I thought I'd check my latest commit to see if I did anything silly: I can confirm the algorithm is working correctly, without any repetition.

Depending on the scale, it can be difficult to look for repeating values on the oscillator, or looking at the wave shape of a recording; so I just added a std::cout<<n<<std::endl and dumped the numeric values in a text file. Here's the result:
https://www.youtube.com/watch?v=pEGvGgB3NPc&feature=youtu.be
