### ISSUE TITLE
Osc.cpp: includes not working on windows

### ISSUE THREAD

**Issue by phdsg** [naus3a/NauModular#9]
getting compiler errors for:
`arpa/inet.h`
and
`sys/select.h`

first answer on the search said to use Winsock2.h instead, but that doesn't cut it.

**Comment by naus3a** [comment]
Yes, Windows does sockets differently than any other OS: I think I'll have to make a few #ifdef blocks with winsock specific isntructions.

I don't have a win machine here, so I'm not sure when I'm going to do it, but it's not going to be anything hard, so I'll definetely give it a try as soon as I have a win machine under my fingers.

**Comment by cschol** [comment]
@naus3a Need help with that? I can provide a PR for the Windows build.

**Comment by naus3a** [comment]
@cschol thanks, I appreciate: I don't have a lot of time at the moment, so if you can handle this we'd speed up the development of this module quite a bit

**Comment by cschol** [comment]
OK. I got it building with the Windows networking functions. What is the best way to test the OSC functions?

**Comment by naus3a** [comment]
Cool!
The current version has only Osc Out working, so that's the feature to be tested.
The module will send messages to a Osc listener on 127.0.0.1:8000, so all you have to do is:

- set up some kind of OSC receiver (max, processing, OF, whatever) listening on that IP/port combo

- plug something meaningful into the "trigger" and "gate" input ports of the module (the top  2 ports). Have a look here for inspiration: https://www.youtube.com/watch?v=kOgQTAJ9bSo

Your receiver should start receiving 2 kind of messages:

/trigger [float]
/gate [float]

**Comment by cschol** [comment]
Perfect. I'll test it out and send the PR.

**Comment by naus3a** [comment]
Thanks :)

**Comment by cschol** [comment]
![image](https://user-images.githubusercontent.com/624427/34956309-bdc4cab2-f9e5-11e7-91fe-0f317a6b2763.png)

:)

**Comment by naus3a** [comment]
flawless victory! :)
